server.port=9090
server.servlet.contextPath=/survey
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/survey?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=info123!
#spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:sqlserver://ipagdevserver:1433;MSSQLSERVER2016=Survey
#spring.datasource.url=jdbc:sqlserver://IPAGDEVSERVER;instanceName=MSSQLSERVER2016;databaseName=Survey;
spring.datasource.url=jdbc:sqlserver://IPAGVMSERVER;databaseName=Survey;
spring.datasource.username=IPAGAPP
spring.datasource.password=Azureapp@2022!
spring.jpa.show-sql=true


spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

server.servlet.session.timeout=120m
logging.level.org.springframework = info
logging.level.tech.hardik = trace

logging.file=D:/spring_app_log_file.log

# To customize logging pattern.
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring.jpa.open-in-view=false

mail_html=D://policySecurity//

#mail properties
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=SecurityBulletin@igglobal.com
spring.mail.password=$3c@678!
mail.from=SecurityBulletin@infogain.com
#mail_cc=gautam.goswami@infogain.com 
mail_cc=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000
spring.mail.properties.mail.smtp.ssl.trust=*

NEW_INTERVIEW_SCHEDULE_EMAIL_BODY=<!DOCTYPE html> <html> <head>    <meta charset="utf-8">    <meta name="viewport" content="width=device-width, initial-scale=1.0">    <meta http-equiv="X-UA-Compatible" content="IE=edge"> </head> <body style="font-family:Arial, Helvetica, sans-serif; font-size: 14px;  line-height: 18px; background-color:#e3e6e8; ">    <table border="0" cellspacing="0" cellpadding="" width="100%">        <tr>            <td align="center">                <table border="0" cellspacing="0" cellpadding="0" width="600" bgColor="white">                    <tr>                        <td style="padding:2px; background-color:#3093ce; ">                        </td>                    </tr>                    <tr>                        <td style="line-height: 18px; padding:15px; background-color:#ffffff; ">                            <p>Dear <strong>[%s]</strong>,</p>                            <p>Thank you once again for accepting and understanding Infogain's Data Security policy.<br/><br/> Please find attached PDF file of policy you accepted.    <br/><br/> <strong>Thanks and Regards,<br/> ISMS Team <br/> <br/> </strong> </td></td> </tr> <td style="padding:2px; background-color:#3093ce; ">                        </td>      </table></body></html> 
